[package]
name = "pass_man"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "2.1.1"
magic-crypt = "3.1.9"
rpassword = "6.0.1"